export * from "./types";
export * from "./music/theory";
export { AttemptClassifier, DEFAULT_THRESHOLDS } from "./trial/AttemptClassifier";
export type { ClassifierThresholds, AttemptInput } from "./trial/AttemptClassifier";
export { RescueLadder, RESCUE_LEVELS, RECOVERY_SCRIPT } from "./trial/RescueLadder";
export { TrialSession } from "./trial/TrialSession";
export type { TrialPhase } from "./trial/TrialSession";
export { Exercise } from "./exercises/Exercise";
export type { CuePlan, TrialRequest, Difficulty } from "./exercises/Exercise";
export { exercises } from "./exercises/registry";
export type { PitchDetector, PitchEstimate } from "./pitch/PitchDetector";
export { AutocorrelationDetector } from "./pitch/AutocorrelationDetector";
export { MicrophoneEngine } from "./pitch/MicrophoneEngine";
export type { MicStatus } from "./pitch/MicrophoneEngine";
export { CuePlayer } from "./audio/CuePlayer";
export { MemoryTrialRepository } from "./storage/TrialRepository";
export type { TrialRepository } from "./storage/TrialRepository";
export { IndexedDbTrialRepository } from "./storage/IndexedDbTrialRepository";
export { KpiCalculator } from "./kpi/KpiCalculator";
export { Recommender } from "./recommend/Recommender";
export type { Recommendation } from "./recommend/Recommender";
