export * from "./types";
export * from "./music/theory";
export { AttemptClassifier, DEFAULT_THRESHOLDS } from "./trial/AttemptClassifier";
export type { ClassifierThresholds, AttemptInput } from "./trial/AttemptClassifier";
export { RescueLadder, RESCUE_LEVELS, RECOVERY_SCRIPT } from "./trial/RescueLadder";
export { TrialSession } from "./trial/TrialSession";
export type { TrialPhase } from "./trial/TrialSession";
export { Exercise } from "./exercises/Exercise";
export type { CuePlan, TrialRequest, Difficulty } from "./exercises/Exercise";
export { exercises } from "./exercises/registry";
export { baselineTestPlan, testProgress } from "./protocol/testPlan";
export type { TestPlan, TestStep, TestProgress } from "./protocol/testPlan";
export type { PitchDetector, PitchEstimate } from "./pitch/PitchDetector";
export { AutocorrelationDetector } from "./pitch/AutocorrelationDetector";
export { MpmDetector } from "./pitch/MpmDetector";
export type { MpmOptions } from "./pitch/MpmDetector";
export { PitchSmoother } from "./pitch/PitchSmoother";
export type { SmootherOptions } from "./pitch/PitchSmoother";
export { MicrophoneEngine } from "./pitch/MicrophoneEngine";
export type { MicStatus, MicListener } from "./pitch/MicrophoneEngine";
export { PitchPipeline } from "./pitch/PitchPipeline";
export type { PitchFrame, NoiseState, PipelineOptions } from "./pitch/PitchPipeline";
export { NoiseFloorTracker } from "./pitch/NoiseFloorTracker";
export type { NoiseFloorOptions } from "./pitch/NoiseFloorTracker";
export { segmentTrace } from "./trial/segmentTrace";
export { heldExtremes } from "./pitch/RangeAnalyzer";
export type { HeldExtremes, RangeAnalyzerOptions } from "./pitch/RangeAnalyzer";
export { practiceDays } from "./kpi/practiceTime";
export { improvementSummary } from "./kpi/improvement";
export type { ImprovementSummary, Movement, RangeMovement } from "./kpi/improvement";
export { pitchZones } from "./kpi/pitchZones";
export type { PitchZone } from "./kpi/pitchZones";
export { SyncClient } from "./sync/SyncClient";
export type { KeyValueStore } from "./sync/SyncClient";
export type { PracticeDay, PracticeTimeOptions } from "./kpi/practiceTime";
export { CuePlayer } from "./audio/CuePlayer";
export { MemoryTrialRepository } from "./storage/TrialRepository";
export type { TrialRepository } from "./storage/TrialRepository";
export { IndexedDbTrialRepository } from "./storage/IndexedDbTrialRepository";
export { KpiCalculator } from "./kpi/KpiCalculator";
export { Recommender } from "./recommend/Recommender";
export type { Recommendation } from "./recommend/Recommender";
