"""Alembic environment: the database comes from Settings, and Postgres upgrades run under an advisory lock.

Several Cloud Run instances can start at once, each running `alembic upgrade
head` from the entrypoint. A transaction-scoped advisory lock serialises them:
the first migrates, the rest wait and then find the schema already at head.
Postgres DDL is transactional, so a failed upgrade leaves the old schema
intact and the previous revision keeps serving.

A caller may pass its own connection in `config.attributes["connection"]`
(the test suite does); otherwise the URL is read from the environment.
"""

from __future__ import annotations

from typing import Any, Literal

import sqlalchemy as sa
from alembic import context
from alembic.autogenerate.api import AutogenContext
from sqlalchemy.dialects import postgresql

from vocal_compass.db import UTCDateTime, make_engine
from vocal_compass.logs import configure_logging
from vocal_compass.models import Base
from vocal_compass.settings import ConfigError, from_env

# Any fixed 64-bit value works; every migrating process just has to agree on it.
MIGRATION_LOCK_KEY = 0x7663_6D69_6772_6174  # "vcmigrat"
# For asking what a column type becomes on Postgres, whichever database autogenerate compares against.
POSTGRESQL = sa.make_url("postgresql+psycopg://").get_dialect()()


def render_item(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
    """Render app column types as plain SQLAlchemy in autogenerated revisions, so migrations never import app code."""
    if type_ != "type":
        return False
    if isinstance(obj, UTCDateTime):
        return "sa.DateTime(timezone=True)"
    if isinstance(obj, sa.JSON) and isinstance(obj.dialect_impl(POSTGRESQL), postgresql.JSONB):
        # Alembic's default rendering of this variant emits an unimported Text().
        autogen_context.imports.add("from sqlalchemy.dialects import postgresql")
        return 'sa.JSON().with_variant(postgresql.JSONB(), "postgresql")'
    return False


def run_migrations(connection: sa.Connection) -> None:
    context.configure(connection=connection, target_metadata=Base.metadata, compare_type=True, render_item=render_item)
    with context.begin_transaction():
        if connection.dialect.name == "postgresql":
            connection.execute(sa.text("SELECT pg_advisory_xact_lock(:key)"), {"key": MIGRATION_LOCK_KEY})
        context.run_migrations()


def main() -> None:
    if context.is_offline_mode():
        raise SystemExit("Offline (--sql) migrations are not supported; run against a database.")
    connection = context.config.attributes.get("connection")
    if connection is not None:
        run_migrations(connection)
        return
    try:
        settings = from_env()
    except ConfigError as exc:
        raise SystemExit(f"Invalid configuration: {exc}") from None
    configure_logging(settings)
    engine = make_engine(settings)
    try:
        with engine.connect() as connection:
            run_migrations(connection)
    finally:
        engine.dispose()


main()
